version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - echo "Zipping package"
      - zip -r9 ../deploy.zip .
  post_build:
     commands:
        - aws lambda update-function-code --function-name journal-login --zip-file fileb://deploy.zip
