version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo "Zipping package"
      - cd node_modules
      - zip -r9 ../deploy.zip .
      - cd ..
      - zip -g deploy.zip **/*
      - echo "Build completed"

   post_build:
      commands:
        - aws lambda update-function-code --function-name journal-login --zip-file fileb://deploy.zip
