phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - echo "Zipping package"
      - cd node_modules
      - zip -r9 ../deploy.zip .
      - cd ..
      - zip -g deploy.zip **/*
   post_build:
     commands:
        - aws lambda update-function-code --function-name journal-login --zip-file fileb://deploy.zip
