AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  journal local


Resources:
  ApiGatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        Register:
          Type: Api
          Properties:
            Path: /register
            Method: POST

        Login:
          Type: Api
          Properties:
            Path: /login
            Method: POST

        Status:
          Type: Api
          Properties:
            Path: /status
            Method: GET
        
        Verify:
          Type: Api
          Properties:
            Path: /verifytoken
            Method: POST